[package]
name = "fuel-execution-trace"
version = "0.1.0"
edition = "2021"

[dependencies]
fuel-core-client.workspace = true
fuel-core-types.workspace = true
fuel-vm.workspace = true

hex.workspace = true
primitive-types.workspace = true
thiserror.workspace = true
tracing.workspace = true
